---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: "{{ template "name" . }}"
  labels:
    app: "{{ .Chart.Name }}"
    release: "{{ .Release.Name }}"
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: "{{ .Values.ingressHost }}"
      http:
        paths:
          - path: "{{ .Values.ingressPath }}"
            backend:
              serviceName: "{{ template "name" . }}"
              servicePort: {{ default .Values.httpPort .Values.ingressServicePort }}
