---
apiVersion: v1
kind: Service
metadata:
  name: "{{ template "name" . }}"
  labels:
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}"
    app: "{{ template "name" . }}"
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}"
    app: "{{ template "name" . }}"
  ports:
  - name: http
    port: {{ .Values.httpPort }}
  - name: transport
    port: {{ .Values.transportPort }}
